// <auto-generated />
namespace MACAWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PersonUserupgrade2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PersonUserupgrade2));
        
        string IMigrationMetadata.Id
        {
            get { return "201907241120107_PersonUser-upgrade2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
