// <auto-generated />
namespace MACAWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PersonUserauto_ID_fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PersonUserauto_ID_fix));
        
        string IMigrationMetadata.Id
        {
            get { return "201907231812326_PersonUser-auto_ID_fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
